### ISSUE TITLE
Failed on .NET7 + ReportPortal.NUnit 4.5.3 + 

### ISSUE THREAD

**Issue by ysparrow** [nvborisenko/reportportal-extensions-insider#2]
Got an error using Insider extention with ReportPortal.NUnit 4.5.3

Error Message:
   System.TypeLoadException : Could not load type 'ReportPortal.Shared.Log' from assembly 'ReportPortal.Shared, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by nvborisenko** [comment]
Happy to see you as an user. I have upgraded packages here, please try the latest v0.3.0, hoping it should be fixed.
