### ISSUE TITLE
Requires an update to work with .NET 8

### ISSUE THREAD

**Issue by ysparrow** [nvborisenko/reportportal-extensions-insider#3]
Looks like the same issue as it was for .NET7 :)

Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
sdk v8.0.204

**Comment by nvborisenko** [comment]
@ysparrow I cannot reproduce it. Can you please help?

**Comment by microbo7** [comment]
I have this error when for ReportPortal.Extensions.Insider.SDK on .net6 - .net8 
But, when  I change  ReportPortal.Extensions.Insider.SDK to ReportPortal.Extensions.Insider everthing works ok. 
Current  configuration  
project sdk - 6
installed sdk - 
  Version:      7.0.18
  Architecture: x64
  Commit:       544c7e6eb3

.NET SDKs installed:
  7.0.408 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

IDE - Rider Build #RD-241.14494.307

OS - Windows 11 Pro 22621.3447

**Comment by ysparrow** [comment]
Please close the issue. Solution from @microbo7 helps. )) Thank you.

**Comment by nvborisenko** [comment]
Installing `ReportPortal.Extensions.Insider` package should not even take effect, in the report you will not see methods with [Insider] attribute. Do you really see it int the Report Portal?
